version: '3.7'

services:
  login:
    image: kamartinez/login-service  # Imagen que ya has subido a Docker Hub
    ports:
      - "8001:8001"  # Exponer el puerto 8001
    networks:
      - auth-network
    depends_on:
      - register  # Asegura que el servicio de Register esté disponible antes de Login

  register:
    image: kamartinez/register-service  # Imagen que ya has subido a Docker Hub
    ports:
      - "8002:8002"  # Exponer el puerto 8002
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
