name: Deploy Authentication Services to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for login and register services
      run: |
        docker build -t kamartinez/login-service ./Login
        docker build -t kamartinez/register-service ./Register

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/login-service
        docker push kamartinez/register-service

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 52.1.37.215  # IP de tu EC2
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Detener y eliminar contenedores anteriores si existen
          docker stop login-service || true
          docker rm login-service || true
          docker stop register-service || true
          docker rm register-service || true

          # Descargar las últimas imágenes de Docker
          docker pull kamartinez/login-service
          docker pull kamartinez/register-service

          # Ejecutar los nuevos contenedores con las imágenes más recientes
          docker run -d --name login-service -p 8001:8001 kamartinez/login-service
          docker run -d --name register-service -p 8002:8002 kamartinez/register-service
