name: Deploy Authentication Services to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for login and register services
      run: |
        docker build -t kamartinez/login-service ./Login
        docker build -t kamartinez/register-service ./Register
        docker build -t kamartinez/login-root ./Login-Root
        docker build -t kamartinez/password ./password-microservice

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/login-service
        docker push kamartinez/register-service
        docker push kamartinez/login-root
        docker push kamartinez/password

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 52.1.37.215 
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # De
          docker stop login-service || true
          docker rm login-service || true
          docker stop register-service || true
          docker rm register-service || true
          docker stop login-root || true
          docker rm login-root || true
          docker stop password || true
          docker rm password || true

          # D
          docker pull kamartinez/login-service
          docker pull kamartinez/register-service
          docker pull kamartinez/login-root
          docker pull kamartinez/password

          # Eje
          docker run -d --name login-service -p 8001:8001 --restart unless-stopped kamartinez/login-service
          docker run -d --name register-service -p 8002:8002 --restart unless-stopped kamartinez/register-service
          docker run -d --name login-root -p 8003:8003 --restart unless-stopped kamartinez/login-root
          docker run -d --name password -p 8003:8003 --restart unless-stopped kamartinez/password
